-- EF-compatible idempotent SQL script for migration: 20260603115037_AddIsAdminToUsers
-- Generated by assistant; review before applying.
SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- 1) Add column if missing
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE Name = N'IsAdmin' AND Object_ID = OBJECT_ID(N'dbo.Users')
)
BEGIN
    ALTER TABLE dbo.Users ADD IsAdmin bit NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT(0);
END

-- 2) Apply UpdateData equivalent from migration (if applicable)
-- Migration sets IsAdmin = false for user with Id = 1; ensure it exists and set value accordingly
IF EXISTS (SELECT 1 FROM dbo.Users WHERE Id = 1)
BEGIN
    UPDATE dbo.Users SET IsAdmin = 0 WHERE Id = 1;
END

-- 3) Insert migration record into __EFMigrationsHistory if missing
IF NOT EXISTS (SELECT 1 FROM dbo.__EFMigrationsHistory WHERE MigrationId = '20260603115037_AddIsAdminToUsers')
BEGIN
    INSERT INTO dbo.__EFMigrationsHistory (MigrationId, ProductVersion)
    VALUES ('20260603115037_AddIsAdminToUsers', '10.0.8');
END

COMMIT TRANSACTION;
GO
